### ISSUE TITLE
Scalable cropSize

### ISSUE THREAD

**Issue by mstottrop** [gekitz/GKImagePicker#1]
Wouldn't it be great if the user could scale/change the cropRectangle?

**Comment by gekitz** [comment]
What would be the use case of a "user changeable crop rect"?

**Comment by mstottrop** [comment]
yep, that's exactly what I meant. Working on it now, would love it on could help :)

**Comment by gekitz** [comment]
I will add it as soon as I have some time. I will also accept a pull request, if you have time to implement it.

**Comment by mstottrop** [comment]
Sounds great.

**Comment by phausero** [comment]
I also vote for implementing the adjustable crop rect :-)
