### ISSUE TITLE
Corp image problem.

### ISSUE THREAD

**Issue by BhaveshDhaduk** [gekitz/GKImagePicker#13]
First of all this is the great code you have written.

I have one issue with cropping image with portrait mode landscape will work fine.

I have change the code to fetch image from library to camera, when I capture image as a landscape mode with camera it will work perfectly, but when I was capture image as portrait image, image shows in corp box as aspect to fit, my image crop box size is 300x 200 means landscape box, in landscape box portrait image not feet well. 

![1](https://f.cloud.github.com/assets/29055/258440/3a70600a-8c98-11e2-84af-f67a14128d6a.PNG)
![2](https://f.cloud.github.com/assets/29055/258441/4a0087ac-8c98-11e2-8900-7b73a299b5cb.PNG)

First image is the current scenario. second image is what I am trying to say.

Because the reason behind If i am crop like a first image it still give (Output result after crop ) me the portrait image not landscape image...

**Comment by gekitz** [comment]
Well and what is the problem?

**Comment by gekitz** [comment]
Afaik the text to this issue appeared now :)
As I tried to reimplement the UIImagePickerController the described behavior is as intended. Try the same scenario with the UIImagePickerController you will get the same result.

Cheers,
Georg

**Comment by BhaveshDhaduk** [comment]
Apple's default UIImagePickerController can't corp image which is smaller size then crop box size, its automatically zoom the size of image and display as per the width of crop box.

Here is only one problem if the crop box is landscape and the image is portrait as i have already upload sample image (Image 1) then crop the image it still portrait, 

if we select crop box landscape then any image will crop forcefully landscape. 

I hope you got my point..

Thanks for your quick reply.
