### ISSUE TITLE
how can i localize strings

### ISSUE THREAD

**Issue by ghost** [gekitz/GKImagePicker#14]
i want to localize the strings like 'choose photo', 'move and scale','use' , and i use the method of - (NSString *)localizedStringForKey:(NSString *)key value:(NSString *)value table:(NSString *)tableName but i don't know the tableName, please help!

**Comment by gekitz** [comment]
Hey!

There is no specific table for that. In the sample project is a Localizable.strings file with the strings in there. You can just exchange them in your project to whatever you want. If you want to extend them, just copy

```
"GKIchoosePhoto" = "Choose Photo";
"GKIuse" = "Use";
"GKImoveAndScale" = "Move and Scale";
"GKIcancel" = "Cancel";
"GKIuse" = "Choose";
```

into your Localizable.strings file.
I'm pretty sure there is a better way to do it, I'm happy about any suggestion.

Cheers,
Georg
