### ISSUE TITLE
Drawing (cropsize) doesn't work on rectangles (not square)

### ISSUE THREAD

**Issue by bernatripoll** [gekitz/GKImagePicker#21]
Hello! this problem happens when the crop size is not a square, like for example 320x80.
- you just pick a photo (no zoom, no moves), then click crop and the result is the original picture.
- Even if you move the photo still not working, I mean it creates a result image but it's not what you selected.

Any suggestions?

Thanks!

**Comment by joshbernfeld** [comment]
This has resulted in problems when cropping to squares (and maybe more not sure).
See issue #23 

Scale is now sometimes determined for the wrong axis because image scale should be based on image width and height, NOT crop width and height.

instead of this

```
if (self.cropSize.width > self.cropSize.height)
```

change it to this

```
if (self.imageToCrop.size.width > self.imageToCrop.size.height)
```
