### ISSUE TITLE
Default zoomed In

### ISSUE THREAD

**Issue by SjoerdPerfors** [gekitz/GKImagePicker#29]
Currently the default setting is Aspect-Fit to display the photo in the Crop viewer. I want this to be zoomed in, so that would be Aspect-Fill. However changing the setting for this is not working:

GKImageCropView.m

Change 

self.imageView.contentMode = UIViewContentModeScaleAspectFit;

to AspectFill in the initWithFrame method:

``` objective-c
- (id)initWithFrame:(CGRect)frame
{
    self = [super initWithFrame:frame];
    if (self) {

        self.userInteractionEnabled = YES;
        self.backgroundColor = [UIColor blackColor];
        self.scrollView = [[ScrollView alloc] initWithFrame:self.bounds ];
        self.scrollView.showsHorizontalScrollIndicator = NO;
        self.scrollView.showsVerticalScrollIndicator = NO;
        self.scrollView.delegate = self;
        self.scrollView.clipsToBounds = NO;
        self.scrollView.decelerationRate = 0.0; 
        self.scrollView.backgroundColor = [UIColor clearColor];
        [self addSubview:self.scrollView];

        self.imageView = [[UIImageView alloc] initWithFrame:self.scrollView.frame];
        self.imageView.contentMode = UIViewContentModeScaleAspectFill;
        self.imageView.backgroundColor = [UIColor blackColor];
        [self.scrollView addSubview:self.imageView];


        self.scrollView.minimumZoomScale = CGRectGetWidth(self.scrollView.frame) / CGRectGetWidth(self.imageView.frame);
        self.scrollView.maximumZoomScale = 20.0;
        [self.scrollView setZoomScale:1.0];
    }
    return self;
}
```

Can anyone point me in the right direction?

**Comment by fvermeulen** [comment]
I have the same problem. If you have a reason. Please let me know.

I also try to fix this

**Comment by SjoerdPerfors** [comment]
In the method layoutSubviews you can change this line:

```
self.imageView.frame = CGRectMake(0, floor((size.height - faktoredHeight) * 0.5), size.width, size.height);
```

by this the width and height of the imageView are set to the cropsize width and height.

But this not the right approach. Now the minimum zoom is wrong and you can't change the image horizontal if it's not a square.

**Comment by joshbernfeld** [comment]
Here I have a solution for you.

In GKImageCropView.m -(void)layoutSubviews 
Replace this

```
if(width > height){
    faktor = width / size.width;
    faktoredWidth = size.width;
    faktoredHeight =  height / faktor;
} else {
    faktor = height / size.height;
    faktoredWidth = width / faktor;
    faktoredHeight =  size.height;
 }
```

With this

```
    //Flip sign, instead of Aspect Fit, will be Aspect Fill.
    //Crop zone is a rectangle
    if (size.width != size.height) {
        if(size.width > size.height){
            faktor = width / size.width;
            faktoredWidth = size.width;
            faktoredHeight =  height / faktor;
        } else {
            faktor = height / size.height;
            faktoredWidth = width / faktor;
            faktoredHeight =  size.height;
        }
    }
    //Crop zone is a square
    else {
        if(width < height){
            faktor = width / size.width;
            faktoredWidth = size.width;
            faktoredHeight =  height / faktor;
        } else {
            faktor = height / size.height;
            faktoredWidth = width / faktor;
            faktoredHeight =  size.height;
        }
    }
```

Then replace the last two lines

```
self.scrollView.contentSize = CGSizeMake(size.width, size.height);
self.imageView.frame = CGRectMake(0, floor((size.height - faktoredHeight) * 0.5), faktoredWidth, faktoredHeight);
```

With these three lines

```
//Content Size was not being set correctly.
self.scrollView.contentSize = CGSizeMake(faktoredWidth, faktoredHeight);
//Center the scrollview in the crop zone.
[self.scrollView setContentOffset:CGPointMake((faktoredWidth-size.width)/2, (faktoredHeight-size.height)/2) animated:NO];
self.imageView.frame = CGRectMake(0, floor((size.height - faktoredHeight/2) * 0.5), faktoredWidth, faktoredHeight);
```

In -(void)init of the same file change contentMode to Aspect Fill, but this doesnt really matter.

```
self.imageView.contentMode = UIViewContentModeScaleAspectFill;
```

Then also to prevent the images from spilling over to the imagepicker during the push transition to the crop view
In GKImageCropViewController.m -(void)viewDidLoad add this to the bottom

```
self.view.clipsToBounds = YES;
```

**Comment by SjoerdPerfors** [comment]
Hi Josh,

Thanks for this. The default view is now aspect fill but the cropped image is now not cropped right and giving me weird results.

Can you have a look at this as well ?

Thanks,
- Sjoerd

**Comment by joshbernfeld** [comment]
Yes I just fixed this problem also, it has to do with cropping squares, in croppedImage method.

Image scale should be based on image width and height, NOT crop width and height.

instead of 

```
if (self.cropSize.width > self.cropSize.height)
```

use

```
if (self.imageToCrop.size.width > self.imageToCrop.size.height)
```

Make sure you are not using your own modifications in this function.

**Comment by SjoerdPerfors** [comment]
Woow works like a charm !

Thanks a lot!

**Comment by joshbernfeld** [comment]
Fantastic!!!

**Comment by joshbernfeld** [comment]
You may also want to take a look at #30

**Comment by fvermeulen** [comment]
It's an improvement for pictures, where the height is bigger than the width. There it is fantastic now. But by images, which are in landscapemode, it does not match. After pressing 'OK' the zooming is not correct, also when i zoomed the picture before to the right size.

Can you help me with this as well?

![bildschirmfoto 2013-08-07 um 11 15 49](https://f.cloud.github.com/assets/1662765/923245/01bce504-ff42-11e2-93a7-f6dab7689449.png)

![bildschirmfoto 2013-08-07 um 11 19 13](https://f.cloud.github.com/assets/1662765/923256/74e7a352-ff42-11e2-9b9f-b21d347a4119.png)

**Comment by SjoerdPerfors** [comment]
Hi Logi, 

I cannot reproduce your problem. Landscape and Portrait images are working here.

**Comment by joshbernfeld** [comment]
Yes, I would love to help.

I have modified my above code to now work with both square and rectangle crop zones. :)

**Comment by fvermeulen** [comment]
Nice Thank you. Now it's perfect :)

Big thanks and a good sleep

**Comment by shuhankuang** [comment]
thanks.
