### ISSUE TITLE
Can I use UIImagePickerControllerSourceTypeCamera with this?

### ISSUE THREAD

**Issue by Shasoosh** [gekitz/GKImagePicker#5]
I've been using GKImagePicker for a while now and I was wondering, is there a way I can take a picture to cropping right from the camera? Thanks

**Comment by gekitz** [comment]
Sure, just add the following line of code before you present the controller

```
//set the source type
self.imagePicker.imagePickerController.sourceType = UIImagePickerControllerSourceTypeCamera;

//present the controller
[self presentModalViewController:self.imagePicker.imagePickerController animated:YES];
```

Hope that helps.
Cheers, Georg

**Comment by leomayleomay** [comment]
@gekitz i don't think GKImagePicker is working with UIImagePickerControllerSourceTypeCamera, the cropSize is not applied to the cropping area after i took a photo, the cropping area is always a square,

@gekitz seems `- (void)imagePickerController:(UIImagePickerController *)picker didFinishPickingImage:(UIImage *)image editingInfo:(NSDictionary *)editingInfo` was not called after picking photo from camera

**Comment by RajChanchal** [comment]
@gekitz , leomayleomay is right, - (void)imagePickerController:(UIImagePickerController *)picker didFinishPickingImage:(UIImage *)image editingInfo:(NSDictionary *)editingInfo is not called for me too.
