### ISSUE TITLE
Memory leak after selecting a picture

### ISSUE THREAD

**Issue by Shasoosh** [gekitz/GKImagePicker#6]
I just noticed that right after I select an image from my camera roll and the crop viewController is opened I get a big memory leak. Is this a known issue or am I doing something wrong?

![Screen Shot 2013-01-20 at 11 05 35 AM](https://f.cloud.github.com/assets/2679978/80979/d840ae2a-62e0-11e2-825e-963a7c4fb26e.png)

Edit: After some digging I believe this is the problematic code under GKImageCropViewController:
- (UIImage *)_toolbarBackgroundImage{
  ..
  ..
  CGGradientRef gradient = CGGradientCreateWithColorComponents(colorSpace, components, NULL, 2);
  
  CGContextDrawLinearGradient(ctx, gradient, CGPointMake(0, 0), CGPointMake(0, 54), kCGImageAlphaNoneSkipFirst);
  ..
  }

After commenting out those lines I lost my toolbar background Image (of course) but I also lost my leaks. And advice would be great.

**Comment by gekitz** [comment]
Fixed this issue in the latest commit.

Cheers,
Georg
